In [1]:
# ==========================================
# Notebook 03 : Feature Engineering
# ==========================================

import os
import sys

import joblib
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# Add project root
sys.path.append(os.path.abspath(".."))

from src.utils import project_name

print(f"Project : {project_name()}")
print("Notebook 03 - Feature Engineering")

Project : FairHire
Notebook 03 - Feature Engineering

In [2]:
# 2. Load the cleaned datasets
resume_df = pd.read_csv("../data/processed/cleaned_resume_dataset.csv")
job_df = pd.read_csv("../data/processed/cleaned_job_dataset.csv")

print("Resume Dataset :", resume_df.shape)
print("Job Dataset :", job_df.shape)

Resume Dataset : (10174, 7)
Job Dataset : (1067, 11)

In [3]:
# 3. Dataset Overview
display(resume_df.head())

display(job_df.head())

,Role,Resume,Decision,Reason_for_decision,Job_Description,Clean_Resume,Clean_Job_Description
0,E-commerce Specialist,Here's a professional resume for Jason Jones:\...,reject,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...,here professional resume jason jones jason jon...,part passionate team forefront machine learnin...
1,Game Developer,Here's a professional resume for Ann Marshall:...,select,Strong technical skills in AI and ML.,Help us build the next-generation products as ...,here professional resume ann marshall ann mars...,help u build nextgeneration product game devel...
2,Human Resources Specialist,Here's a professional resume for Patrick Mccla...,reject,Insufficient system design expertise for senio...,We need a Human Resources Specialist to enhanc...,here professional resume patrick mcclain patri...,need human resource specialist enhance team te...
3,E-commerce Specialist,Here's a professional resume for Patricia Gray...,select,Impressive leadership and communication abilit...,Be part of a passionate team at the forefront ...,here professional resume patricia gray patrici...,part passionate team forefront cloud computing...
4,E-commerce Specialist,Here's a professional resume for Amanda Gross:...,reject,Lacked leadership skills for a senior position.,We are looking for an experienced E-commerce S...,here professional resume amanda gross amanda g...,looking experienced ecommerce specialist join ...

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords,Clean_Skills,Clean_Responsibilities,Clean_Keywords,Clean_Job_Text
0,NET-F-001,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Framework; .NET Core f...,Assist in coding and debugging applications; L...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,c vbnet basic net framework net core fundament...,assist coding debugging application learn appl...,net c aspnet mvc entity framework sql server l...,.NET Developer c vbnet basic net framework net...
1,NET-F-002,.NET Developer,Fresher,0-1,C#; .NET Framework basics; ASP.NET; Razor; HTM...,Write simple C# programs under guidance; Suppo...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,c net framework basic aspnet razor html cs jav...,write simple c program guidance support develo...,net c aspnet mvc entity framework sql server r...,.NET Developer c net framework basic aspnet ra...
2,NET-F-003,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Core; ASP.NET MVC; HTM...,Contribute to development of small modules; As...,.NET; C#; ASP.NET MVC; SQL Server; Entity Fram...,c vbnet basic net core aspnet mvc html cs java...,contribute development small module assist bug...,net c aspnet mvc sql server entity framework git,.NET Developer c vbnet basic net core aspnet m...
3,NET-F-004,.NET Developer,Fresher,0-1,C#; .NET Framework; ASP.NET basics; SQL Server...,Support in software design documentation; Assi...,.NET; C#; SQL Server; Entity Framework; ASP.NET,c net framework aspnet basic sql server html c...,support software design documentation assist s...,net c sql server entity framework aspnet,.NET Developer c net framework aspnet basic sq...
4,NET-F-005,.NET Developer,Fresher,0-1,C#; ASP.NET; MVC; Entity Framework basics; SQL...,Learn to design and build ASP.NET applications...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...,c aspnet mvc entity framework basic sql server...,learn design build aspnet application assist c...,net c aspnet mvc entity framework sql server,.NET Developer c aspnet mvc entity framework b...

In [4]:
# 4. Check Required Columns
print("Resume Columns")
print(resume_df.columns)

print("\nJob Columns")
print(job_df.columns)

Resume Columns
Index(['Role', 'Resume', 'Decision', 'Reason_for_decision', 'Job_Description',
       'Clean_Resume', 'Clean_Job_Description'],
      dtype='str')

Job Columns
Index(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills',
       'Responsibilities', 'Keywords', 'Clean_Skills',
       'Clean_Responsibilities', 'Clean_Keywords', 'Clean_Job_Text'],
      dtype='str')

In [5]:
# 5. Use only the cleaned resume as input

X = resume_df["Clean_Resume"]

# Encode the target labels
y = resume_df["Decision"].map({
    "reject": 0,
    "select": 1
})

print("Number of samples:", len(X))
print("Number of labels :", len(y))

print("\nLabel Distribution")
print(y.value_counts())

Number of samples: 10174
Number of labels : 10174

Label Distribution
Decision
0    5114
1    5060
Name: count, dtype: int64

In [6]:
# 6. Convert Text into TF-IDF Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95
)

X_tfidf = tfidf.fit_transform(X)

print("TF-IDF matrix shape:", X_tfidf.shape)

TF-IDF matrix shape: (10174, 5000)

In [7]:
# 7. Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples :", X_train.shape[0])
print("Testing samples  :", X_test.shape[0])

Training samples : 8139
Testing samples  : 2035

In [8]:
# 8. Save the TF-IDF vectorizer and the datasets
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(
    tfidf,
    "../models/tfidf_vectorizer.pkl"
)

print("TF-IDF vectorizer saved successfully.")

TF-IDF vectorizer saved successfully.

In [9]:
# 9. View some of the learned vocabulary

feature_names = tfidf.get_feature_names_out()

print("Total Features:", len(feature_names))

print("\nFirst 50 Features:\n")
print(feature_names[:50])

Total Features: 5000

First 50 Features:

['10' '10 increase' '10 year' '100' '1000' '10000' '12' '123'
 '123 4567890' '123 main' '12345' '12345 phone' '12345 professional'
 '1234567' '1234567 email' '1234567 linkedin' '1234567890'
 '1234567890 linkedin' '15' '15 improvement' '15 increase' '15 reduction'
 '1st' '20' '20 improvement' '20 increase' '20 reduction' '200' '20052009'
 '2008' '20082012' '2010' '2010 skill' '20102012' '20102012 bachelor'
 '20102014' '20102014 achievement' '20102014 certification'
 '20102014 skill' '2012' '20122015' '2013' '2013 achievement' '2013 skill'
 '2014' '2015' '2015 2018' '2015 achievement' '2015 bachelor'
 '2015 certification']

In [10]:
# 10. Save the training and testing datasets
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(X_train, "../models/X_train.pkl")
joblib.dump(X_test, "../models/X_test.pkl")

joblib.dump(y_train, "../models/y_train.pkl")
joblib.dump(y_test, "../models/y_test.pkl")

print("Training and testing datasets saved successfully.")

Training and testing datasets saved successfully.

# **Summary**

## Objective
Convert the cleaned textual data into numerical features suitable for machine learning.

## Tasks Completed
- Loaded cleaned datasets
- Combined resume and job description into a single input feature
- Encoded the target labels
- Generated TF-IDF features
- Split the dataset into training and testing sets
- Saved the trained TF-IDF vectorizer
- Saved the training and testing datasets

## Output Files
models/
- tfidf_vectorizer.pkl
- X_train.pkl
- X_test.pkl
- y_train.pkl
- y_test.pkl

The processed data is now ready for machine learning model training.